apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: npm-webhook-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-trigger
      bindings:
        - ref: npm-trigger-binding
      template:
        ref: npm-trigger-template

