apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-webhook-listener-resolver
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-trigger
      bindings:
        - ref: build-and-push-trigger-binding-resolver
      template:
        ref: build-and-push-trigger-template-resolver

