apiVersion: v1
kind: ConfigMap
metadata:
  name: maven-settings-cm
data:
  settings.xml: |
    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 
                                  https://maven.apache.org/xsd/settings-1.0.0.xsd">
      <profiles>
        <profile>
          <id>default</id>
          <repositories>
            <repository>
              <id>central</id>
              <name>Maven Central</name>
              <url>https://repo.maven.apache.org/maven2</url>
              <releases>
                <enabled>true</enabled>
              </releases>
              <snapshots>
                <enabled>false</enabled>
              </snapshots>
            </repository>
          </repositories>
        </profile>
      </profiles>
      <activeProfiles>
        <activeProfile>default</activeProfile>
      </activeProfiles>
    </settings>
