apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-push-pipeline
  # Adjust the namespace as needed
spec:
  params:
    - name: git-url
      description: The Git repository URL to clone
    - name: git-revision
      description: The branch or commit to check out 
      default: "main"
    - name: repo-name
      description: The Quay.io repository name 

  workspaces:
    - name: shared-workspace
      description: Workspace for sharing source code and build artifacts between tasks.
    - name: maven-settings
      configmap:
        name: maven-settings-cm

  tasks:
    # 1. Clone the source code repository
    - name: clone-repo
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: "$(params.git-url)"
        - name: revision
          value: "$(params.git-revision)"
      workspaces:
        - name: output
          workspace: shared-workspace

    # 2. Build the application using Maven after the repo is cloned
    - name: build-app
      runAfter:
        - clone-repo
      taskRef:
        kind: ClusterTask
        name: maven
      params:
        - name: GOALS
          value:
            - clean
            - package
      workspaces:
        - name: source
          workspace: shared-workspace

    # 3. Build the container image once the app is successfully built
    - name: build-image
      runAfter:
        - build-app
      taskRef:
        kind: ClusterTask
        name: buildah
      params:
        - name: IMAGE
          value: "quay.io/mramadan83/$(params.repo-name):$(tasks.clone-repo.results.commit)"
        - name: STORAGE
          value: "overlay"
        - name: TLSVERIFY
          value: "true"
        - name: FORMAT
          value: "oci"
        - name: DOCKERFILE
          value: "/workspace/source/Dockerfile"
      workspaces:
        - name: source
          workspace: shared-workspace

    # 4. Push the built image to Quay.io after the image is created
    - name: push-image
      runAfter:
        - build-image
      taskRef:
        kind: ClusterTask
        name: buildah
      params:
        - name: IMAGE
          value: "quay.io/mramadan83/$(params.repo-name):$(tasks.clone-repo.results.commit)"
        - name: STORAGE
          value: "overlay"
        - name: TLSVERIFY
          value: "true"
        - name: FORMAT
          value: "oci"
        - name: DESTINATION
          value: "docker://quay.io/mramadan83/$(params.repo-name):$(tasks.clone-repo.results.commit)"
        - name: AUTHFILE
          value: "/tekton/credentials/.dockerconfigjson"
      workspaces:
        - name: source
          workspace: shared-workspace
